-- ==============================================================================
-- PJzen | Tabela de Registro de Entrada e Saída de Acessos no Supabase
-- Execute este script no SQL Editor do seu painel Supabase (https://supabase.com)
-- ==============================================================================

CREATE TABLE IF NOT EXISTS acessos_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_evento TEXT NOT NULL,                      -- 'entrada' ou 'saida'
    horario TEXT NOT NULL,                           -- Data e Horário (Horário de Brasília)
    ip TEXT NOT NULL,                                -- IP do computador / dispositivo visitante
    pagina TEXT,                                     -- Página acessada (ex: /, /view/..., /documento/...)
    dispositivo TEXT,                                -- Aparelho / Navegador do usuário
    session_id TEXT,                                 -- ID único da sessão (vincula a entrada à saída)
    tempo_permanencia_segundos INTEGER DEFAULT 0,    -- Tempo no site em segundos (enviado na saída)
    host TEXT,                                       -- Domínio ativo na Hostinger
    created_at TIMESTAMPTZ DEFAULT NOW()             -- Timestamp automático do Supabase
);

-- Índices para buscas rápidas no painel
CREATE INDEX IF NOT EXISTS idx_acessos_tipo ON acessos_logs(tipo_evento);
CREATE INDEX IF NOT EXISTS idx_acessos_ip ON acessos_logs(ip);
CREATE INDEX IF NOT EXISTS idx_acessos_created ON acessos_logs(created_at DESC);

-- Habilitar Row Level Security (RLS)
ALTER TABLE acessos_logs ENABLE ROW LEVEL SECURITY;

-- Política de Segurança: Permitir inserção de registros de acesso pelo site
DROP POLICY IF EXISTS "Permitir insercao de logs de acesso" ON acessos_logs;
CREATE POLICY "Permitir insercao de logs de acesso" 
ON acessos_logs FOR INSERT 
WITH CHECK (true);

-- Política de Segurança: Permitir leitura pelo painel e administradores
DROP POLICY IF EXISTS "Permitir leitura de logs de acesso" ON acessos_logs;
CREATE POLICY "Permitir leitura de logs de acesso" 
ON acessos_logs FOR SELECT 
USING (true);
